### ISSUE TITLE
[question] Hi i want to make a dockerfile (and docker-compose file) for this.

### ISSUE THREAD

**Issue by ranomier** [Naereen/Nginx-Fancyindex-Theme#13]
Are you interested in supporting them through your repo or should i do one myself?

If i do it myself, i wouldt fork you work. My dockerfile would clone this repo.

If i do it in here, i could copy the files directly into the docker image :)

Greetings :)

**Comment by Naereen** [comment]
Hi @ranomier,
Thanks for your interest :pray:.

I have no interest at all in docker, and will not consider testing any dockerfile, or other "container" technology.
So you are most welcome to do this on your own! Just respect the terms of [the license](https://github.com/Naereen/Nginx-Fancyindex-Theme/blob/master/LICENSE) of this repository, and do whatever you want :smiley:. (mainly this part of the license, "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.", please respect it)

But I must say I'm curious: what exactly do you expect to "contain" in this dockerfile? A ready-to-use nginx server + the fancy_index plugin + this configuration?
Because [Nginx-Fancyindex-Theme](https://github.com/Naereen/Nginx-Fancyindex-Theme/) is far from being self-contained.

Regards.

**Comment by ranomier** [comment]
This is xkcd? A very cool one.
The funny thing is, docker is the split screen function, in this example. (If done right) :3

I will look at the submodule solution. One thing i use, when i clone, is --depth=1, too minimize the image footprint. Maybe this is posibil with submodules too.

Good day and thank you for you suggestions :)
